
spring:
  application:
    name: streams-app
  kafka:
    streams:
      bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: retrieveClaimCount
    stream:
      kafka:
        binder:
          configuration:
            commit.interval.ms: 100
            default:
              key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          consumer:
            configuration:
              value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          claimEvents-in-0:
            consumer:
              configuration:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          claimProcessor-in-0:
            consumer:
              configuration:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          claimRequestProcessor-in-0:
            consumer:
              configuration:
                value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      function:
        #definition: claimProcessor;claimRequestProcessor;claimEvents
        definition: claimEvents
      bindings:
        claimProcessor-in-0:
            destination: CLAIMS
        claimProcessor-out-0:
            destination: sinkinput
        claimRequestProcessor-in-0:
            destination: sinkinput
        claimRequestProcessor-out-0:
            destination: sinkoutput
        claimEvents-in-0:
            destination: event-count
        claimEvents-out-0:
            destination: streamout
server:
  port: 8081