apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-deployment
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: my-app-deployment
    spec:
      containers:
        #- image: docker.io/achalise/claimservice:latest
        - image: claimservice:0.0.1-SNAPSHOT
          name: claimservice
          env:
            - name: spring_profiles_active
              value: cf
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: kafka-secrets
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: kafka-secrets
          resources: {}