apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-app-deployment
  name: my-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: my-app-deployment
  type: NodePort
status:
  loadBalancer: {}